name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant Build Permission
        run: chmod +x ./gradlew

      - name: Build Debug
        run: ./gradlew assembleDebug

      - name: Build Release
        run: ./gradlew assembleRelease
